### PR TITLE
fix: prevent angles bigger than 180 degrees

### PR DESCRIPTION
**Pull request by MLopezJ**
use shortestRotation method to prevent angle increase more than 180 on 'onRotate'

### CODE REVIEW

**Comment by Lenakh97** [comment]
My bad. I think this rotation can be 360(?) We should figure that out before merging. It so, we should make a new function for preventing it to be more than 360 degrees.

**Comment by coderbyheart** [comment]
Yes, [as discussed today, `rotationDeg` can be 0-359](https://github.com/NordicPlayground/robot-war-app/pull/35/files#diff-c33fe0e0e14592ec037bd4b30cfafd87a41d97da9bd171b2c65ae8be12f11fa0R123-R138).

**Review by coderbyheart — CHANGES_REQUESTED** [review]
Rotation [can be 0-359](https://github.com/NordicPlayground/robot-war-app/pull/35/files#diff-c33fe0e0e14592ec037bd4b30cfafd87a41d97da9bd171b2c65ae8be12f11fa0R123-R138).

**Comment by MLopezJ** [comment]
Changes related this fix are addressed in https://github.com/NordicPlayground/robot-war-app/pull/42

**Pull request closed without merging**
